### ISSUE TITLE
Proper naming scheme

### ISSUE THREAD

**Issue by clang99** [Shugabuga/Silica#25]
Thanks for the great implementation! However it needs a proper naming scheme.

Styles->settings
docs->upload
util->scripts
index.py->build.py
setup.sh, requirements.txt to be moved to scripts folder

Folder names should be statically defined in settings.json, it would make it a lot easier to rename in future and avoid any conflicts.

And finally support for github deploy keys, keep up the good work 👍

**Comment by Shugabuga** [comment]
>  docs->upload

Not possible. Blame GitHub for that. The current nomenclature for the output folder (which should actually be named `dist`, if anything), is for easy deploying to GitHub Pages.

> Styles->settings

Most of the assets here are style-related. As for the capital, it's to indicate "hey, this is where you can edit things!"

> util->scripts

This is just for helper functions. I don't think renaming things would make a difference.

> index.py->build.py

Probably the only one I may consider, but it may break build scripts, so I'd refrain.

> setup.sh, requirements.txt to be moved to scripts folder

But why? They're supposed to be easy to spot, especially if someone didn't bother reading the README.

> Folder names should be statically defined in settings.json, it would make it a lot easier to rename in future and avoid any conflicts.

There should never be conflicts. Store Silica in its own folder, please. It's designed to be contained to its own Git repo and used with GitHub Pages, after all.

> And finally support for github deploy keys, keep up the good work 👍

I don't think this is a Silica issue, but if you do wish to use deploy keys instead, check out [this gist](https://gist.github.com/zhujunsan/a0becf82ade50ed06115) because it seems helpful.

---

Overall, to me, these reads as a bunch of personal preferences rather than compliance to a spec like PEP3 (which, if I recall, Silica flagrantly breaks at times, which *is* a problem). Additionally, renaming stuff without a *really* good reason can break people's setups, which should be avoided at all costs. Even when I eventually rewrite Silica, I'm keeping as many files in the same place as possible.

Sorry, but I'm tagging this as wont-fix and closing it.

**Comment by clang99** [comment]
This was never meant to be an issue related post, but rather an enhancement to folder structure with clean, easy to recognize names and better UX. It's currently very confusing to work with which many users will agree to.
Statically defining folder names would enable backwards compatibility and freedom of naming scheme.
And again, thank you for the work done!
